### PR TITLE
Use white-space: pre; with popular project description

### LINKED ISSUE #529: Most popular featured projects doesn't show new lines as new lines in the description
### Describe the bug. What is going wrong?

Most popular featured projects doesn't show new lines as new lines in the description

### What is causing the bug?

New lines are generally not rendered as such in HTML

### Anything else?

Easy fix

### PR DESCRIPTION
**Pull request by mybearworld**
Resolves #529

### CODE REVIEW

File: features/most-popular-project.js [hunk 1]
```diff
@@ -76,6 +76,7 @@ function addBox(title, id, views, instructions) {
   thumbnail.style.width = "300px";
   p.style.textAlign = "left";
   p.style.float = "left";
+  p.style.whiteSpace = "pre";
```
Comment (rgantzos) [inline features/most-popular-project.js:79]: This should be `pre-line`, not just `pre`. Otherwise, the text will spill over outside of where it should be.

**Review by rgantzos — CHANGES_REQUESTED** [review]

File: features/most-popular-project.js (hunk 1 above)
Comment (mybearworld) [reply features/most-popular-project.js]: :+1:

**Review by rgantzos — APPROVED** [review]

**Review by MaterArc — APPROVED** [review]
Now it looks good, yeah that change was needed or it looks funky lol
